from fastapi import APIRouter, Depends, HTTPException
from pydantic import BaseModel
import uuid

router = APIRouter(prefix="/contracts")

class CreateContractRequest(BaseModel):
    job_id: str
        talent_id: str
            gross_amount_usd: float

            @router.post("/create")
            async def create_contract(payload: CreateContractRequest):
                # TODO: Add auth check - only enterprise_client can create
                    # 1. Verify job belongs to caller
                        # 2. Create contract in 'draft' status
                            # 3. Call billing to create escrow intent
                                fee = payload.gross_amount_usd * 0.10
                                    payout = payload.gross_amount_usd - fee
                                        return {
                                                "contract_id": str(uuid.uuid4()),
                                                        "gross": payload.gross_amount_usd,
                                                                "fee_10_percent": fee,
                                                                        "talent_payout": payout,
                                                                                "status": "draft - waiting for escrow funding"
                                                                                    }

                                                                                    @router.post("/{contract_id}/release")
                                                                                    async def release_escrow(contract_id: str):
                                                                                        # Only call after work is approved
                                                                                            # This is where you'd call stripe.Transfer.create to talent
                                                                                                return {"status": "released", "contract_id": contract_id}
                                                                                                import os
                                                                                                import uuid
                                                                                                import psycopg2
                                                                                                from psycopg2.extras import RealDictCursor
                                                                                                from fastapi import APIRouter, Depends, HTTPException
                                                                                                from pydantic import BaseModel, Field
                                                                                                from auth import get_current_user

                                                                                                DATABASE_URL = os.getenv("DATABASE_URL")
                                                                                                router = APIRouter(prefix="/contracts", tags=["contracts"])

                                                                                                class CreateContractRequest(BaseModel):
                                                                                                    job_id: str
                                                                                                        talent_id: str
                                                                                                            gross_amount_usd: float = Field(gt=0, le=1000000)

                                                                                                            class MessageCreate(BaseModel):
                                                                                                                body: str = Field(min_length=1, max_length=5000)

                                                                                                                def get_db():
                                                                                                                    return psycopg2.connect(DATABASE_URL, cursor_factory=RealDictCursor)

                                                                                                                    @router.post("/create", status_code=201)
                                                                                                                    async def create_contract(payload: CreateContractRequest, current_user = Depends(get_current_user)):
                                                                                                                        if current_user['role']!= 'enterprise_client':
                                                                                                                                raise HTTPException(status_code=403, detail="Only clients can create contracts")

                                                                                                                                    conn = get_db()
                                                                                                                                        cur = conn.cursor()
                                                                                                                                            try:
                                                                                                                                                    # Verify job belongs to this client and is open
                                                                                                                                                            cur.execute("SELECT id, client_id, status, budget_usd FROM jobs WHERE id = %s", (payload.job_id,))
                                                                                                                                                                    job = cur.fetchone()
                                                                                                                                                                            if not job:
                                                                                                                                                                                        raise HTTPException(status_code=404, detail="Job not found")
                                                                                                                                                                                                if str(job['client_id'])!= current_user['user_id']:
                                                                                                                                                                                                            raise HTTPException(status_code=403, detail="Not your job")
                                                                                                                                                                                                                    if job['status']!= 'open':
                                                                                                                                                                                                                                raise HTTPException(status_code=400, detail=f"Job is {job['status']}, not open")

                                                                                                                                                                                                                                        # Verify talent exists
                                                                                                                                                                                                                                                cur.execute("SELECT id FROM users WHERE id = %s AND role = 'ai_talent'", (payload.talent_id,))
                                                                                                                                                                                                                                                        if not cur.fetchone():
                                                                                                                                                                                                                                                                    raise HTTPException(status_code=404, detail="Talent not found")

                                                                                                                                                                                                                                                                            # Calculate 10% fee - THIS IS YOUR PLATFORM RULE
                                                                                                                                                                                                                                                                                    gross = payload.gross_amount_usd
                                                                                                                                                                                                                                                                                            fee_percent = 10
                                                                                                                                                                                                                                                                                                    fee_usd = round(gross * (fee_percent / 100), 2)
                                                                                                                                                                                                                                                                                                            payout_usd = round(gross - fee_usd, 2)

                                                                                                                                                                                                                                                                                                                    contract_id = str(uuid.uuid4())
                                                                                                                                                                                                                                                                                                                            cur.execute("""
                                                                                                                                                                                                                                                                                                                                        INSERT INTO contracts (id, job_id, client_id, talent_id, gross_amount_usd, platform_fee_percent, platform_fee_usd, talent_payout_usd, status)
                                                                                                                                                                                                                                                                                                                                                    VALUES (%s, %s, %s, %s, %s, %s, %s, %s, 'draft')
                                                                                                                                                                                                                                                                                                                                                                RETURNING id
                                                                                                                                                                                                                                                                                                                                                                        """, (contract_id, payload.job_id, current_user['user_id'], payload.talent_id, gross, fee_percent, fee_usd, payout_usd))

                                                                                                                                                                                                                                                                                                                                                                                # Create escrow ledger entry
                                                                                                                                                                                                                                                                                                                                                                                        cur.execute("""
                                                                                                                                                                                                                                                                                                                                                                                                    INSERT INTO escrow_ledger (contract_id, amount_total_cents, fee_cents, payout_cents, status)
                                                                                                                                                                                                                                                                                                                                                                                                                VALUES (%s, %s, %s, %s, 'pending')
                                                                                                                                                                                                                                                                                                                                                                                                                        """, (contract_id, int(gross*100), int(fee_usd*100), int(payout_usd*100)))

                                                                                                                                                                                                                                                                                                                                                                                                                                # Mark job in_progress
                                                                                                                                                                                                                                                                                                                                                                                                                                        cur.execute("UPDATE jobs SET status = 'in_progress' WHERE id = %s", (payload.job_id,))

                                                                                                                                                                                                                                                                                                                                                                                                                                                conn.commit()
                                                                                                                                                                                                                                                                                                                                                                                                                                                        return {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    "contract_id": contract_id,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                "job_id": payload.job_id,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            "gross_amount_usd": gross,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        "platform_fee_10_percent": fee_usd,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    "talent_payout_usd": payout_usd,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                "status": "draft - now fund via /billing/create-escrow-intent",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            "next_step": f"POST /api/v1/billing/create-escrow-intent with contract_id {contract_id}"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        except HTTPException:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                raise
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    except Exception as e:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            conn.rollback()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    raise HTTPException(status_code=500, detail=str(e))
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        finally:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                cur.close()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        conn.close()

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        @router.get("/{contract_id}")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        async def get_contract(contract_id: str, current_user = Depends(get_current_user)):
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            conn = get_db()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                cur = conn.cursor()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    try:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            cur.execute("""
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        SELECT c.*, j.title as job_title, u1.email as client_email, u2.email as talent_email
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    FROM contracts c
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                JOIN jobs j ON c.job_id = j.id
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            JOIN users u1 ON c.client_id = u1.id
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        JOIN users u2 ON c.talent_id = u2.id
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    WHERE c.id = %s
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            """, (contract_id,))
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    row = cur.fetchone()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            if not row:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        raise HTTPException(status_code=404, detail="Contract not found")

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                # Only participants can view
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        if current_user['user_id'] not in [str(row['client_id']), str(row['talent_id'])] and current_user['role']!= 'super_admin':
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    raise HTTPException(status_code=403, detail="Not authorized")

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            return {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        "id": str(row['id']),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    "job_title": row['job_title'],
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                "gross": float(row['gross_amount_usd']),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            "fee": float(row['platform_fee_usd']),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        "payout": float(row['talent_payout_usd']),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    "status": row['status'],
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                "client": row['client_email'],
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            "talent": row['talent_email']
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        finally:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                cur.close()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        conn.close()

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        @router.post("/{contract_id}/messages")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        async def post_message(contract_id: str, msg: MessageCreate, current_user = Depends(get_current_user)):
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            conn = get_db()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                cur = conn.cursor()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    try:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            cur.execute("SELECT client_id, talent_id FROM contracts WHERE id = %s", (contract_id,))
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    c = cur.fetchone()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            if not c:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        raise HTTPException(status_code=404, detail="Contract not found")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                if current_user['user_id'] not in [str(c['client_id']), str(c['talent_id'])]:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            raise HTTPException(status_code=403, detail="Not participant")

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    cur.execute("""
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                INSERT INTO messages (contract_id, sender_id, body) VALUES (%s, %s, %s) RETURNING id, created_at
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        """, (contract_id, current_user['user_id'], msg.body))
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                row = cur.fetchone()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        conn.commit()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                return {"message_id": str(row['id']), "created_at": str(row['created_at'])}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    finally:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            cur.close()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    conn.close()

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    @router.get("/{contract_id}/messages")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    async def get_messages(contract_id: str, current_user = Depends(get_current_user)):
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        conn = get_db()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            cur = conn.cursor()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                try:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        cur.execute("SELECT * FROM messages WHERE contract_id = %s ORDER BY created_at ASC LIMIT 100", (contract_id,))
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                rows = cur.fetchall()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        return {"messages": [{"id": str(r['id']), "sender_id": str(r['sender_id']), "body": r['body'], "created_at": str(r['created_at'])} for r in rows]}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            finally:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    cur.close()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            conn.close()