import { useEffect, useState } from 'react';

type Props = { contractId: string; token: string; isClient: boolean };

export default function ContractView({ contractId, token, isClient }: Props) {
  const [contract, setContract] = useState<any>(null);
    const [messages, setMessages] = useState<any[]>([]);
      const [newMsg, setNewMsg] = useState('');
        const [loading, setLoading] = useState(false);

          const fetchContract = async () => {
              const res = await fetch(`http://localhost:8000/api/v1/contracts/${contractId}`, {
                    headers: { 'Authorization': `Bearer ${token}` }
                        });
                            const data = await res.json();
                                setContract(data);
                                  };

                                    const fetchMessages = async () => {
                                        const res = await fetch(`http://localhost:8000/api/v1/contracts/${contractId}/messages`, {
                                              headers: { 'Authorization': `Bearer ${token}` }
                                                  });
                                                      const data = await res.json();
                                                          setMessages(data.messages || []);
                                                            };

                                                              useEffect(() => {
                                                                  fetchContract();
                                                                      fetchMessages();
                                                                          const interval = setInterval(fetchMessages, 3000);
                                                                              return () => clearInterval(interval);
                                                                                }, [contractId]);

                                                                                  const handleRelease = async () => {
                                                                                      if (!confirm(`Release $${contract?.payout} to talent? Platform keeps $${contract?.fee} (10%)`)) return;
                                                                                          setLoading(true);
                                                                                              try {
                                                                                                    const res = await fetch(`http://localhost:8000/api/v1/billing/release`, {
                                                                                                            method: 'POST',
                                                                                                                    headers: { 'Content-Type': 'application/json', 'Authorization': `Bearer ${token}` },
                                                                                                                            body: JSON.stringify({ contract_id: contractId })
                                                                                                                                  });
                                                                                                                                        const data = await res.json();
                                                                                                                                              if (!res.ok) throw new Error(data.detail);
                                                                                                                                                    alert(`Released! Transfer: ${data.transfer_id}`);
                                                                                                                                                          fetchContract();
                                                                                                                                                              } catch (e: any) {
                                                                                                                                                                    alert(e.message);
                                                                                                                                                                        } finally {
                                                                                                                                                                              setLoading(false);
                                                                                                                                                                                  }
                                                                                                                                                                                    };

                                                                                                                                                                                      const handleFund = async () => {
                                                                                                                                                                                          setLoading(true);
                                                                                                                                                                                              try {
                                                                                                                                                                                                    const res = await fetch(`http://localhost:8000/api/v1/billing/create-escrow-intent`, {
                                                                                                                                                                                                            method: 'POST',
                                                                                                                                                                                                                    headers: { 'Content-Type': 'application/json', 'Authorization': `Bearer ${token}` },
                                                                                                                                                                                                                            body: JSON.stringify({ contract_id: contractId, gross_amount_usd: contract.gross })
                                                                                                                                                                                                                                  });
                                                                                                                                                                                                                                        const data = await res.json();
                                                                                                                                                                                                                                              if (!res.ok) throw new Error(data.detail);
                                                                                                                                                                                                                                                    alert(`Escrow Intent created: ${data.payment_intent_id}\nClient Secret: ${data.client_secret}\n\nIn real app, use Stripe Elements to confirm payment.`);
                                                                                                                                                                                                                                                          fetchContract();
                                                                                                                                                                                                                                                              } catch (e: any) {
                                                                                                                                                                                                                                                                    alert(e.message);
                                                                                                                                                                                                                                                                        } finally {
                                                                                                                                                                                                                                                                              setLoading(false);
                                                                                                                                                                                                                                                                                  }
                                                                                                                                                                                                                                                                                    };

                                                                                                                                                                                                                                                                                      const sendMessage = async (e: React.FormEvent) => {
                                                                                                                                                                                                                                                                                          e.preventDefault();
                                                                                                                                                                                                                                                                                              if (!newMsg.trim()) return;
                                                                                                                                                                                                                                                                                                  await fetch(`http://localhost:8000/api/v1/contracts/${contractId}/messages`, {
                                                                                                                                                                                                                                                                                                        method: 'POST',
                                                                                                                                                                                                                                                                                                              headers: { 'Content-Type': 'application/json', 'Authorization': `Bearer ${token}` },
                                                                                                                                                                                                                                                                                                                    body: JSON.stringify({ body: newMsg })
                                                                                                                                                                                                                                                                                                                        });
                                                                                                                                                                                                                                                                                                                            setNewMsg('');
                                                                                                                                                                                                                                                                                                                                fetchMessages();
                                                                                                                                                                                                                                                                                                                                  };

                                                                                                                                                                                                                                                                                                                                    if (!contract) return <div className="p-6 text-white">Loading contract...</div>;

                                                                                                                                                                                                                                                                                                                                      return (
                                                                                                                                                                                                                                                                                                                                          <div className="bg-zinc-900 border border-zinc-800 rounded-xl p-6 space-y-6 text-white">
                                                                                                                                                                                                                                                                                                                                                <div>
                                                                                                                                                                                                                                                                                                                                                        <h2 className="text-2xl font-bold">{contract.job_title}</h2>
                                                                                                                                                                                                                                                                                                                                                                <p className="text-zinc-400 text-sm mt-1">Contract {contractId.slice(0,8)} | Status: <span className="text-purple-400 font-bold">{contract.status}</span></p>
                                                                                                                                                                                                                                                                                                                                                                      </div>

                                                                                                                                                                                                                                                                                                                                                                            <div className="grid grid-cols-3 gap-4 bg-black p-4 rounded border border-zinc-800">
                                                                                                                                                                                                                                                                                                                                                                                    <div><p className="text-zinc-500 text-xs">GROSS</p><p className="text-xl font-bold">${contract.gross}</p></div>
                                                                                                                                                                                                                                                                                                                                                                                            <div><p className="text-zinc-500 text-xs">PLATFORM FEE 10%</p><p className="text-xl font-bold text-red-400">${contract.fee}</p></div>
                                                                                                                                                                                                                                                                                                                                                                                                    <div><p className="text-zinc-500 text-xs">TALENT GETS</p><p className="text-xl font-bold text-green-400">${contract.payout}</p></div>
                                                                                                                                                                                                                                                                                                                                                                                                          </div>

                                                                                                                                                                                                                                                                                                                                                                                                                <div className="flex gap-3">
                                                                                                                                                                                                                                                                                                                                                                                                                        {contract.status === 'draft' && isClient && (
                                                                                                                                                                                                                                                                                                                                                                                                                                  <button onClick={handleFund} disabled={loading} className="bg-yellow-600 hover:bg-yellow-700 px-6 py-2 rounded font-bold">Fund Escrow</button>
                                                                                                                                                                                                                                                                                                                                                                                                                                          )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                  {(contract.status === 'funded' || contract.status === 'active') && isClient && (
                                                                                                                                                                                                                                                                                                                                                                                                                                                            <button onClick={handleRelease} disabled={loading} className="bg-green-600 hover:bg-green-700 px-6 py-2 rounded font-bold">✓ Approve & Release 90% to Talent</button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <div className="border-t border-zinc-800 pt-6">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <h3 className="font-bold mb-3">Chat (per contract)</h3>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <div className="bg-black border border-zinc-800 rounded h-64 overflow-y-auto p-3 space-y-2 mb-3">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          {messages.map((m: any) => (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <div key={m.id} className="text-sm"><span className="text-zinc-500 text-xs">{m.created_at.slice(11,19)}</span> <span className="text-purple-300">{m.sender_id.slice(0,6)}:</span> {m.body}</div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          {messages.length === 0 && <p className="text-zinc-600 text-sm">No messages yet</p>}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <form onSubmit={sendMessage} className="flex gap-2">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <input value={newMsg} onChange={e => setNewMsg(e.target.value)} placeholder="Type message..." className="flex-1 bg-black border border-zinc-700 p-2 rounded text-white" />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <button className="bg-zinc-800 px-4 py-2 rounded">Send</button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </form>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }