import os
import uuid
import psycopg2
from psycopg2.extras import RealDictCursor
from passlib.context import CryptContext

DATABASE_URL = os.getenv("DATABASE_URL")
if not DATABASE_URL:
    DATABASE_URL = "postgresql://nexus_admin:super_secure_local_dev_password@localhost:5432/nexus_ai_ledger"

    pwd_context = CryptContext(schemes=["bcrypt"], deprecated="auto")

    def get_hash(password: str):
        return pwd_context.hash(password)

        def seed():
            conn = psycopg2.connect(DATABASE_URL, cursor_factory=RealDictCursor)
                cur = conn.cursor()
                    print("🌱 Seeding NexusAI database...")

                        try:
                                # Clear old test data if exists (optional - comment out in production)
                                        # cur.execute("DELETE FROM messages; DELETE FROM escrow_ledger; DELETE FROM contracts; DELETE FROM jobs; DELETE FROM talent_profiles; DELETE FROM users WHERE email LIKE '%@test.nexusai.dev';")

                                                # 1. Super Admin
                                                        admin_id = str(uuid.uuid4())
                                                                admin_email = "admin@nexusai.dev"
                                                                        cur.execute("SELECT id FROM users WHERE email = %s", (admin_email,))
                                                                                if not cur.fetchone():
                                                                                            cur.execute("""
                                                                                                            INSERT INTO users (id, email, password_hash, role, first_name, last_name, company_name, country_iso, is_verified)
                                                                                                                            VALUES (%s, %s, %s, 'super_admin'::user_role, 'Platform', 'Admin', 'NexusAI', 'US', TRUE)
                                                                                                                                        """, (admin_id, admin_email, get_hash("Admin123!@#")))
                                                                                                                                                    print(f"✅ Admin created: {admin_email} / Admin123!@#")

                                                                                                                                                            # 2. Enterprise Client - AlphaCorp
                                                                                                                                                                    client_id = str(uuid.uuid4())
                                                                                                                                                                            client_email = "hiring@alphacorp.ai"
                                                                                                                                                                                    cur.execute("SELECT id FROM users WHERE email = %s", (client_email,))
                                                                                                                                                                                            existing = cur.fetchone()
                                                                                                                                                                                                    if not existing:
                                                                                                                                                                                                                cur.execute("""
                                                                                                                                                                                                                                INSERT INTO users (id, email, password_hash, role, first_name, last_name, company_name, country_iso, is_verified)
                                                                                                                                                                                                                                                VALUES (%s, %s, %s, 'enterprise_client'::user_role, 'Sarah', 'Connor', 'AlphaCorp Inc.', 'US', TRUE)
                                                                                                                                                                                                                                                            """, (client_id, client_email, get_hash("alphacorp123")))
                                                                                                                                                                                                                                                                        print(f"✅ Client created: {client_email} / alphacorp123")
                                                                                                                                                                                                                                                                                else:
                                                                                                                                                                                                                                                                                            client_id = str(existing['id'])

                                                                                                                                                                                                                                                                                                    # 3. AI Talent - Amara (Nigeria)
                                                                                                                                                                                                                                                                                                            talent1_id = str(uuid.uuid4())
                                                                                                                                                                                                                                                                                                                    talent1_email = "amara@test.nexusai.dev"
                                                                                                                                                                                                                                                                                                                            cur.execute("SELECT id FROM users WHERE email = %s", (talent1_email,))
                                                                                                                                                                                                                                                                                                                                    if not cur.fetchone():
                                                                                                                                                                                                                                                                                                                                                cur.execute("""
                                                                                                                                                                                                                                                                                                                                                                INSERT INTO users (id, email, password_hash, role, first_name, last_name, country_iso, is_verified)
                                                                                                                                                                                                                                                                                                                                                                                VALUES (%s, %s, %s, 'ai_talent'::user_role, 'Amara', 'Chukwu', 'NG', TRUE)
                                                                                                                                                                                                                                                                                                                                                                                            """, (talent1_id, talent1_email, get_hash("talent123")))
                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                    cur.execute("""
                                                                                                                                                                                                                                                                                                                                                                                                                                    INSERT INTO talent_profiles (user_id, skills_tags, bio, years_experience, target_hourly_rate, sandbox_aggregate_score, portfolio_url)
                                                                                                                                                                                                                                                                                                                                                                                                                                                    VALUES (%s, ARRAY['PyTorch', 'LLM-Fine-Tuning', 'Docker', 'Transformers'], 'Senior NLP Expert - 6 years building LLM pipelines for fintech. Ex-Andela.', 6, 65.00, 98.40, 'https://github.com/amara')
                                                                                                                                                                                                                                                                                                                                                                                                                                                                """, (talent1_id,))
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            print(f"✅ Talent 1 created: {talent1_email} / talent123 - 98.4 score")

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    # 4. AI Talent - Raj (India)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            talent2_id = str(uuid.uuid4())
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    talent2_email = "raj@test.nexusai.dev"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            cur.execute("SELECT id FROM users WHERE email = %s", (talent2_email,))
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    if not cur.fetchone():
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                cur.execute("""
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                INSERT INTO users (id, email, password_hash, role, first_name, last_name, country_iso, is_verified)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                VALUES (%s, %s, %s, 'ai_talent'::user_role, 'Raj', 'Patel', 'IN', TRUE)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            """, (talent2_id, talent2_email, get_hash("talent123")))
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    cur.execute("""
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    INSERT INTO talent_profiles (user_id, skills_tags, bio, years_experience, target_hourly_rate, sandbox_aggregate_score, portfolio_url)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    VALUES (%s, ARRAY['TensorFlow', 'Computer Vision', 'Kubernetes', 'MLOps'], 'Computer Vision Engineer - Built detection models for manufacturing.', 4, 45.00, 92.10, 'https://github.com/raj')
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                """, (talent2_id,))
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            print(f"✅ Talent 2 created: {talent2_email} / talent123 - 92.1 score")

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    # 5. Sample Job for testing
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            cur.execute("SELECT id FROM jobs WHERE title = %s", ("Build RAG Chatbot for Docs",))
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    if not cur.fetchone():
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                job_id = str(uuid.uuid4())
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            cur.execute("""
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            INSERT INTO jobs (id, client_id, title, description, budget_usd, required_skills, status)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            VALUES (%s, %s, %s, %s, %s, %s, 'open')
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        """, (job_id, client_id, "Build RAG Chatbot for Docs", "Need a RAG system using LlamaIndex + Qdrant to answer questions over 10k PDFs. Must handle multi-language. Budget includes infra.", 2500.00, ["LLM-Fine-Tuning", "PyTorch", "RAG"]))
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    print(f"✅ Sample job created: Build RAG Chatbot - $2500")

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            conn.commit()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    print("\n🎉 Seeding complete!")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            print("\n--- LOGIN CREDENTIALS ---")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    print("Admin: admin@nexusai.dev / Admin123!@#")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            print("Client: hiring@alphacorp.ai / alphacorp123")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    print("Talent 1: amara@test.nexusai.dev / talent123")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            print("Talent 2: raj@test.nexusai.dev / talent123")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    print("-------------------------\n")

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        except Exception as e:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                conn.rollback()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        print(f"❌ Seed failed: {e}")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                raise e
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    finally:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            cur.close()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    conn.close()

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    if __name__ == "__main__":
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        seed()