import os
import time
import psycopg2
from psycopg2.extensions import ISOLATION_LEVEL_AUTOCOMMIT

DB_URL = os.getenv("DATABASE_URL")
if not DB_URL:
    DB_URL = "postgresql://nexus_admin:super_secure_local_dev_password@localhost:5432/nexus_ai_ledger"
        print("⚠️  WARNING: Using fallback DB_URL - set DATABASE_URL in .env for production")

        TABLES_SQL = """
        -- Enable UUID extension
        CREATE EXTENSION IF NOT EXISTS "pgcrypto";

        -- Enums - Fixed typo 'disverted' -> 'disputed'
        DO $$ BEGIN
            IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'user_role') THEN 
                    CREATE TYPE user_role AS ENUM ('super_admin', 'enterprise_client', 'ai_talent'); 
                        END IF;
                            IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'contract_status') THEN 
                                    CREATE TYPE contract_status AS ENUM ('draft', 'funded', 'active', 'completed', 'disputed', 'cancelled'); 
                                        END IF;
                                            IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'sandbox_status') THEN 
                                                    CREATE TYPE sandbox_status AS ENUM ('queued', 'running', 'passed', 'failed'); 
                                                        END IF;
                                                            IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'job_status') THEN 
                                                                    CREATE TYPE job_status AS ENUM ('open', 'in_progress', 'closed', 'cancelled'); 
                                                                        END IF;
                                                                        END $$;

                                                                        -- Users table (from your original)
                                                                        CREATE TABLE IF NOT EXISTS users (
                                                                            id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
                                                                                email VARCHAR(255) UNIQUE NOT NULL,
                                                                                    password_hash VARCHAR(255) NOT NULL,
                                                                                        role user_role NOT NULL,
                                                                                            first_name VARCHAR(100) NOT NULL,
                                                                                                last_name VARCHAR(100) NOT NULL,
                                                                                                    company_name VARCHAR(255),
                                                                                                        country_iso VARCHAR(2) NOT NULL,
                                                                                                            is_verified BOOLEAN DEFAULT FALSE,
                                                                                                                stripe_account_id VARCHAR(255),
                                                                                                                    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
                                                                                                                    );
                                                                                                                    CREATE INDEX IF NOT EXISTS idx_users_email ON users(email);
                                                                                                                    CREATE INDEX IF NOT EXISTS idx_users_role ON users(role);

                                                                                                                    -- Talent profiles
                                                                                                                    CREATE TABLE IF NOT EXISTS talent_profiles (
                                                                                                                        id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
                                                                                                                            user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE UNIQUE,
                                                                                                                                skills_tags TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
                                                                                                                                    bio TEXT DEFAULT '',
                                                                                                                                        years_experience INT NOT NULL DEFAULT 0,
                                                                                                                                            target_hourly_rate NUMERIC(10,2) NOT NULL DEFAULT 0.00,
                                                                                                                                                sandbox_aggregate_score NUMERIC(5,2) DEFAULT 0.00,
                                                                                                                                                    portfolio_url TEXT,
                                                                                                                                                        availability VARCHAR(20) DEFAULT 'available',
                                                                                                                                                            updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
                                                                                                                                                            );

                                                                                                                                                            -- JOBS - MISSING BEFORE - Clients post work
                                                                                                                                                            CREATE TABLE IF NOT EXISTS jobs (
                                                                                                                                                                id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
                                                                                                                                                                    client_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
                                                                                                                                                                        title VARCHAR(255) NOT NULL,
                                                                                                                                                                            description TEXT NOT NULL,
                                                                                                                                                                                budget_usd NUMERIC(10,2) NOT NULL CHECK (budget_usd > 0),
                                                                                                                                                                                    required_skills TEXT[] NOT NULL,
                                                                                                                                                                                        status job_status DEFAULT 'open',
                                                                                                                                                                                            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                                                                                                                                                                                                closed_at TIMESTAMP
                                                                                                                                                                                                );
                                                                                                                                                                                                CREATE INDEX IF NOT EXISTS idx_jobs_client ON jobs(client_id);
                                                                                                                                                                                                CREATE INDEX IF NOT EXISTS idx_jobs_status ON jobs(status);
                                                                                                                                                                                                CREATE INDEX IF NOT EXISTS idx_jobs_skills ON jobs USING GIN(required_skills);

                                                                                                                                                                                                -- CONTRACTS - MISSING BEFORE - Links job + talent + escrow
                                                                                                                                                                                                CREATE TABLE IF NOT EXISTS contracts (
                                                                                                                                                                                                    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
                                                                                                                                                                                                        job_id UUID NOT NULL REFERENCES jobs(id) ON DELETE CASCADE,
                                                                                                                                                                                                            client_id UUID NOT NULL REFERENCES users(id),
                                                                                                                                                                                                                talent_id UUID NOT NULL REFERENCES users(id),
                                                                                                                                                                                                                    gross_amount_usd NUMERIC(10,2) NOT NULL CHECK (gross_amount_usd > 0),
                                                                                                                                                                                                                        platform_fee_percent INT NOT NULL DEFAULT 10 CHECK (platform_fee_percent >= 0 AND platform_fee_percent <= 30),
                                                                                                                                                                                                                            platform_fee_usd NUMERIC(10,2) NOT NULL,
                                                                                                                                                                                                                                talent_payout_usd NUMERIC(10,2) NOT NULL,
                                                                                                                                                                                                                                    status contract_status DEFAULT 'draft',
                                                                                                                                                                                                                                        escrow_stripe_payment_intent_id VARCHAR(255),
                                                                                                                                                                                                                                            escrow_stripe_transfer_id VARCHAR(255),
                                                                                                                                                                                                                                                funded_at TIMESTAMP,
                                                                                                                                                                                                                                                    completed_at TIMESTAMP,
                                                                                                                                                                                                                                                        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
                                                                                                                                                                                                                                                        );
                                                                                                                                                                                                                                                        CREATE INDEX IF NOT EXISTS idx_contracts_client ON contracts(client_id);
                                                                                                                                                                                                                                                        CREATE INDEX IF NOT EXISTS idx_contracts_talent ON contracts(talent_id);
                                                                                                                                                                                                                                                        CREATE INDEX IF NOT EXISTS idx_contracts_job ON contracts(job_id);

                                                                                                                                                                                                                                                        -- ESCROW LEDGER - MISSING BEFORE - Audit trail for 10% fee
                                                                                                                                                                                                                                                        CREATE TABLE IF NOT EXISTS escrow_ledger (
                                                                                                                                                                                                                                                            id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
                                                                                                                                                                                                                                                                contract_id UUID NOT NULL REFERENCES contracts(id) ON DELETE CASCADE UNIQUE,
                                                                                                                                                                                                                                                                    amount_total_cents INT NOT NULL CHECK (amount_total_cents > 0),
                                                                                                                                                                                                                                                                        fee_cents INT NOT NULL CHECK (fee_cents >= 0),
                                                                                                                                                                                                                                                                            payout_cents INT NOT NULL CHECK (payout_cents > 0),
                                                                                                                                                                                                                                                                                currency VARCHAR(3) DEFAULT 'usd',
                                                                                                                                                                                                                                                                                    stripe_payment_intent_id VARCHAR(255),
                                                                                                                                                                                                                                                                                        stripe_transfer_id VARCHAR(255),
                                                                                                                                                                                                                                                                                            status VARCHAR(20) DEFAULT 'pending',
                                                                                                                                                                                                                                                                                                released_at TIMESTAMP,
                                                                                                                                                                                                                                                                                                    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
                                                                                                                                                                                                                                                                                                    );

                                                                                                                                                                                                                                                                                                    -- MESSAGES - MISSING BEFORE - Client <-> Talent chat per contract
                                                                                                                                                                                                                                                                                                    CREATE TABLE IF NOT EXISTS messages (
                                                                                                                                                                                                                                                                                                        id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
                                                                                                                                                                                                                                                                                                            contract_id UUID NOT NULL REFERENCES contracts(id) ON DELETE CASCADE,
                                                                                                                                                                                                                                                                                                                sender_id UUID NOT NULL REFERENCES users(id),
                                                                                                                                                                                                                                                                                                                    body TEXT NOT NULL CHECK (char_length(body) > 0 AND char_length(body) <= 5000),
                                                                                                                                                                                                                                                                                                                        is_read BOOLEAN DEFAULT FALSE,
                                                                                                                                                                                                                                                                                                                            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
                                                                                                                                                                                                                                                                                                                            );
                                                                                                                                                                                                                                                                                                                            CREATE INDEX IF NOT EXISTS idx_messages_contract ON messages(contract_id);
                                                                                                                                                                                                                                                                                                                            CREATE INDEX IF NOT EXISTS idx_messages_sender ON messages(sender_id);

                                                                                                                                                                                                                                                                                                                            -- REVIEWS - MISSING BEFORE
                                                                                                                                                                                                                                                                                                                            CREATE TABLE IF NOT EXISTS reviews (
                                                                                                                                                                                                                                                                                                                                id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
                                                                                                                                                                                                                                                                                                                                    contract_id UUID NOT NULL REFERENCES contracts(id) ON DELETE CASCADE UNIQUE,
                                                                                                                                                                                                                                                                                                                                        reviewer_id UUID NOT NULL REFERENCES users(id),
                                                                                                                                                                                                                                                                                                                                            reviewee_id UUID NOT NULL REFERENCES users(id),
                                                                                                                                                                                                                                                                                                                                                rating INT NOT NULL CHECK (rating >=1 AND rating <=5),
                                                                                                                                                                                                                                                                                                                                                    comment TEXT,
                                                                                                                                                                                                                                                                                                                                                        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
                                                                                                                                                                                                                                                                                                                                                        );

                                                                                                                                                                                                                                                                                                                                                        -- SANDBOX SUBMISSIONS - Track code tests
                                                                                                                                                                                                                                                                                                                                                        CREATE TABLE IF NOT EXISTS sandbox_submissions (
                                                                                                                                                                                                                                                                                                                                                            id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
                                                                                                                                                                                                                                                                                                                                                                talent_id UUID NOT NULL REFERENCES users(id),
                                                                                                                                                                                                                                                                                                                                                                    challenge_id VARCHAR(100) NOT NULL,
                                                                                                                                                                                                                                                                                                                                                                        code_body TEXT NOT NULL,
                                                                                                                                                                                                                                                                                                                                                                            status sandbox_status DEFAULT 'queued',
                                                                                                                                                                                                                                                                                                                                                                                output TEXT,
                                                                                                                                                                                                                                                                                                                                                                                    score NUMERIC(5,2) DEFAULT 0.00,
                                                                                                                                                                                                                                                                                                                                                                                        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
                                                                                                                                                                                                                                                                                                                                                                                        );
                                                                                                                                                                                                                                                                                                                                                                                        CREATE INDEX IF NOT EXISTS idx_sandbox_talent ON sandbox_submissions(talent_id);
                                                                                                                                                                                                                                                                                                                                                                                        """

                                                                                                                                                                                                                                                                                                                                                                                        def init_db():
                                                                                                                                                                                                                                                                                                                                                                                            print("🔧 Connecting to DB...")
                                                                                                                                                                                                                                                                                                                                                                                                for attempt in range(10):
                                                                                                                                                                                                                                                                                                                                                                                                        try:
                                                                                                                                                                                                                                                                                                                                                                                                                    conn = psycopg2.connect(DB_URL)
                                                                                                                                                                                                                                                                                                                                                                                                                                conn.set_isolation_level(ISOLATION_LEVEL_AUTOCOMMIT)
                                                                                                                                                                                                                                                                                                                                                                                                                                            cursor = conn.cursor()
                                                                                                                                                                                                                                                                                                                                                                                                                                                        cursor.execute(TABLES_SQL)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    print("✅ NexusAI Database provisioned successfully!")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                print("   Tables: users, talent_profiles, jobs, contracts, escrow_ledger, messages, reviews, sandbox_submissions")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            cursor.close()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        conn.close()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    return
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            except Exception as e:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        print(f"⏳ DB not ready, attempt {attempt+1}/10: {e}")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    time.sleep(3)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        print("❌ Failed to init DB after 10 attempts")

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        if __name__ == "__main__":
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            init_db()