from fastapi import APIRouter
from pydantic import BaseModel
from typing import List

router = APIRouter(prefix="/jobs")

class JobCreate(BaseModel):
    title: str
        description: str
            budget_usd: float
                required_skills: List[str]

                @router.post("/create")
                async def post_job(job: JobCreate):
                    # Insert into jobs table
                        return {"status": "job_posted", "title": job.title}

                        @router.get("/search")
                        async def search_jobs(skill: str = ""):
                            # SELECT * FROM jobs WHERE skill = ANY(required_skills)
                                return {"results": []}
                                import os
                                import uuid
                                from typing import List, Optional
                                import psycopg2
                                from psycopg2.extras import RealDictCursor
                                from fastapi import APIRouter, Depends, HTTPException, Query
                                from pydantic import BaseModel, Field
                                from auth import get_current_user

                                DATABASE_URL = os.getenv("DATABASE_URL")
                                router = APIRouter(prefix="/jobs", tags=["jobs"])

                                class JobCreate(BaseModel):
                                    title: str = Field(min_length=5, max_length=255)
                                        description: str = Field(min_length=20, max_length=5000)
                                            budget_usd: float = Field(gt=0, le=1000000)
                                                required_skills: List[str] = Field(min_length=1, max_length=20)

                                                class JobResponse(BaseModel):
                                                    id: str
                                                        client_id: str
                                                            title: str
                                                                description: str
                                                                    budget_usd: float
                                                                        required_skills: List[str]
                                                                            status: str
                                                                                created_at: str

                                                                                def get_db():
                                                                                    conn = psycopg2.connect(DATABASE_URL, cursor_factory=RealDictCursor)
                                                                                        return conn

                                                                                        @router.post("/create", response_model=JobResponse, status_code=201)
                                                                                        async def post_job(job: JobCreate, current_user = Depends(get_current_user)):
                                                                                            if current_user['role']!= 'enterprise_client' and current_user['role']!= 'super_admin':
                                                                                                    raise HTTPException(status_code=403, detail="Only clients can post jobs")

                                                                                                        conn = get_db()
                                                                                                            cur = conn.cursor()
                                                                                                                try:
                                                                                                                        job_id = str(uuid.uuid4())
                                                                                                                                cur.execute("""
                                                                                                                                            INSERT INTO jobs (id, client_id, title, description, budget_usd, required_skills, status)
                                                                                                                                                        VALUES (%s, %s, %s, %s, %s, %s, 'open')
                                                                                                                                                                    RETURNING id, client_id, title, description, budget_usd, required_skills, status, created_at
                                                                                                                                                                            """, (job_id, current_user['user_id'], job.title, job.description, job.budget_usd, job.required_skills))
                                                                                                                                                                                    row = cur.fetchone()
                                                                                                                                                                                            conn.commit()
                                                                                                                                                                                                    return {
                                                                                                                                                                                                                "id": str(row['id']),
                                                                                                                                                                                                                            "client_id": str(row['client_id']),
                                                                                                                                                                                                                                        "title": row['title'],
                                                                                                                                                                                                                                                    "description": row['description'],
                                                                                                                                                                                                                                                                "budget_usd": float(row['budget_usd']),
                                                                                                                                                                                                                                                                            "required_skills": row['required_skills'],
                                                                                                                                                                                                                                                                                        "status": row['status'],
                                                                                                                                                                                                                                                                                                    "created_at": str(row['created_at'])
                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                finally:
                                                                                                                                                                                                                                                                                                                        cur.close()
                                                                                                                                                                                                                                                                                                                                conn.close()

                                                                                                                                                                                                                                                                                                                                @router.get("/search")
                                                                                                                                                                                                                                                                                                                                async def search_jobs(
                                                                                                                                                                                                                                                                                                                                    skill: Optional[str] = Query(None, description="Filter by skill"),
                                                                                                                                                                                                                                                                                                                                        min_budget: Optional[float] = Query(None, ge=0),
                                                                                                                                                                                                                                                                                                                                            max_budget: Optional[float] = Query(None, ge=0),
                                                                                                                                                                                                                                                                                                                                                limit: int = Query(20, le=100)
                                                                                                                                                                                                                                                                                                                                                ):
                                                                                                                                                                                                                                                                                                                                                    conn = get_db()
                                                                                                                                                                                                                                                                                                                                                        cur = conn.cursor()
                                                                                                                                                                                                                                                                                                                                                            try:
                                                                                                                                                                                                                                                                                                                                                                    query = "SELECT j.*, u.company_name FROM jobs j JOIN users u ON j.client_id = u.id WHERE j.status = 'open'"
                                                                                                                                                                                                                                                                                                                                                                            params = []
                                                                                                                                                                                                                                                                                                                                                                                    if skill:
                                                                                                                                                                                                                                                                                                                                                                                                query += " AND %s = ANY(j.required_skills)"
                                                                                                                                                                                                                                                                                                                                                                                                            params.append(skill)
                                                                                                                                                                                                                                                                                                                                                                                                                    if min_budget is not None:
                                                                                                                                                                                                                                                                                                                                                                                                                                query += " AND j.budget_usd >= %s"
                                                                                                                                                                                                                                                                                                                                                                                                                                            params.append(min_budget)
                                                                                                                                                                                                                                                                                                                                                                                                                                                    if max_budget is not None:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                query += " AND j.budget_usd <= %s"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            params.append(max_budget)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    query += " ORDER BY j.created_at DESC LIMIT %s"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            params.append(limit)

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    cur.execute(query, tuple(params))
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            rows = cur.fetchall()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    return {"results": [
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                "id": str(r['id']),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                "title": r['title'],
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                "company": r['company_name'],
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                "budget": float(r['budget_usd']),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                "skills": r['required_skills'],
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                "created_at": str(r['created_at'])
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            } for r in rows
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ]}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        finally:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                cur.close()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        conn.close()

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        @router.get("/{job_id}")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        async def get_job(job_id: str):
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            conn = get_db()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                cur = conn.cursor()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    try:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            cur.execute("SELECT j.*, u.company_name, u.email as client_email FROM jobs j JOIN users u ON j.client_id = u.id WHERE j.id = %s", (job_id,))
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    row = cur.fetchone()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            if not row:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        raise HTTPException(status_code=404, detail="Job not found")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                return {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            "id": str(row['id']),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        "title": row['title'],
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    "description": row['description'],
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                "budget_usd": float(row['budget_usd']),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            "skills": row['required_skills'],
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        "status": row['status'],
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    "company": row['company_name'],
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                "client_id": str(row['client_id'])
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            finally:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    cur.close()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            conn.close()