import { useState } from 'react';
import { useRouter } from 'next/router';

export default function Login() {
  const [email, setEmail] = useState('hiring@alphacorp.ai');
    const [password, setPassword] = useState('alphacorp123');
      const [loading, setLoading] = useState(false);
        const router = useRouter();

          const handleLogin = async (e: React.FormEvent) => {
              e.preventDefault();
                  setLoading(true);
                      try {
                            const form = new URLSearchParams();
                                  form.append('username', email);
                                        form.append('password', password);

                                              const res = await fetch('http://localhost:8000/api/v1/auth/login', {
                                                      method: 'POST',
                                                              headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
                                                                      body: form.toString()
                                                                            });
                                                                                  const data = await res.json();
                                                                                        if (!res.ok) throw new Error(data.detail || 'Login failed');

                                                                                              localStorage.setItem('nexus_token', data.access_token);
                                                                                                    localStorage.setItem('nexus_role', data.role);
                                                                                                          localStorage.setItem('nexus_user_id', data.user_id);

                                                                                                                if (data.role === 'enterprise_client') router.push('/dashboard/client');
                                                                                                                      else if (data.role === 'ai_talent') router.push('/dashboard/talent');
                                                                                                                            else router.push('/dashboard/admin');

                                                                                                                                } catch (err: any) {
                                                                                                                                      alert(err.message);
                                                                                                                                          } finally {
                                                                                                                                                setLoading(false);
                                                                                                                                                    }
                                                                                                                                                      };

                                                                                                                                                        return (
                                                                                                                                                            <div className="min-h-screen bg-black flex items-center justify-center p-6">
                                                                                                                                                                  <div className="bg-zinc-900 border border-zinc-800 p-8 rounded-xl w-full max-w-md">
                                                                                                                                                                          <h1 className="text-2xl font-black text-white mb-2">NexusAI Login</h1>
                                                                                                                                                                                  <p className="text-zinc-500 text-sm mb-6">Test accounts from seed_data.py</p>
                                                                                                                                                                                          <form onSubmit={handleLogin} className="space-y-4">
                                                                                                                                                                                                    <select
                                                                                                                                                                                                                onChange={e => {
                                                                                                                                                                                                                              const v = e.target.value.split('|');
                                                                                                                                                                                                                                            setEmail(v[0]); setPassword(v[1]);
                                                                                                                                                                                                                                                        }}
                                                                                                                                                                                                                                                                    className="w-full bg-black border border-zinc-700 p-3 rounded text-white text-sm"
                                                                                                                                                                                                                                                                              >
                                                                                                                                                                                                                                                                                          <option value="hiring@alphacorp.ai|alphacorp123">Client: hiring@alphacorp.ai / alphacorp123</option>
                                                                                                                                                                                                                                                                                                      <option value="amara@test.nexusai.dev|talent123">Talent 1: amara@test.nexusai.dev / talent123 (98.4)</option>
                                                                                                                                                                                                                                                                                                                  <option value="raj@test.nexusai.dev|talent123">Talent 2: raj@test.nexusai.dev / talent123 (92.1)</option>
                                                                                                                                                                                                                                                                                                                              <option value="admin@nexusai.dev|Admin123!@#">Admin: admin@nexusai.dev / Admin123!@#</option>
                                                                                                                                                                                                                                                                                                                                        </select>
                                                                                                                                                                                                                                                                                                                                                  <input value={email} onChange={e => setEmail(e.target.value)} placeholder="Email" className="w-full bg-black border border-zinc-700 p-3 rounded text-white" required />
                                                                                                                                                                                                                                                                                                                                                            <input value={password} onChange={e => setPassword(e.target.value)} type="password" placeholder="Password" className="w-full bg-black border border-zinc-700 p-3 rounded text-white" required />
                                                                                                                                                                                                                                                                                                                                                                      <button disabled={loading} className="w-full bg-purple-600 hover:bg-purple-700 text-white py-3 rounded font-bold">
                                                                                                                                                                                                                                                                                                                                                                                  {loading? 'Logging in...' : 'Login'}
                                                                                                                                                                                                                                                                                                                                                                                            </button>
                                                                                                                                                                                                                                                                                                                                                                                                    </form>
                                                                                                                                                                                                                                                                                                                                                                                                            <div className="mt-6 text-xs text-zinc-600">
                                                                                                                                                                                                                                                                                                                                                                                                                      <p>Backend: http://localhost:8000/docs</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                <p>Flow: Login → Post Job → Search Talent → Create Contract → Fund Escrow → Release 90%</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                    );
                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                    import Login from '../components/Login';
                                                                                                                                                                                                                                                                                                                                                                                                                                                    export default function LoginPage() { return <Login />; }