import { useState, useEffect } from 'react';
import ContractView from '../../components/ContractView';

export default function TalentDashboard() {
  const [token, setToken] = useState('');
    const [jobs, setJobs] = useState<any[]>([]);
      const [activeContractId, setActiveContractId] = useState('');
        const [profile, setProfile] = useState<any>(null);

          useEffect(() => {
              const t = localStorage.getItem('nexus_token') || '';
                  setToken(t);
                      fetchJobs();
                          fetchMe();
                            }, []);

                              const fetchMe = async () => {
                                  const res = await fetch('http://localhost:8000/api/v1/auth/me', {
                                        headers: { 'Authorization': `Bearer ${localStorage.getItem('nexus_token')}` }
                                            });
                                                if (res.ok) {
                                                      const data = await res.json();
                                                            setProfile(data);
                                                                }
                                                                  };

                                                                    const fetchJobs = async () => {
                                                                        const res = await fetch('http://localhost:8000/api/v1/jobs/search?limit=20');
                                                                            const data = await res.json();
                                                                                setJobs(data.results || []);
                                                                                  };

                                                                                    const handleConnectStripe = async () => {
                                                                                        const res = await fetch('http://localhost:8000/api/v1/billing/connect-stripe', {
                                                                                              method: 'POST',
                                                                                                    headers: { 'Authorization': `Bearer ${token}` }
                                                                                                        });
                                                                                                            const data = await res.json();
                                                                                                                if (res.ok) {
                                                                                                                      alert(`Stripe account ${data.stripe_account_id} created. Open onboarding: ${data.onboarding_url}`);
                                                                                                                            window.open(data.onboarding_url, '_blank');
                                                                                                                                } else {
                                                                                                                                      alert(data.detail);
                                                                                                                                          }
                                                                                                                                            };

                                                                                                                                              const applyToJob = async (job: any) => {
                                                                                                                                                  const talentId = localStorage.getItem('nexus_user_id');
                                                                                                                                                      const gross = job.budget;
                                                                                                                                                          if (!confirm(`Apply to ${job.title} for $${gross}? Client will pay $${(gross*0.1).toFixed(2)} fee, you get $${(gross*0.9).toFixed(2)}`)) return;

                                                                                                                                                              const res = await fetch('http://localhost:8000/api/v1/contracts/create', {
                                                                                                                                                                    method: 'POST',
                                                                                                                                                                          headers: { 'Content-Type': 'application/json', 'Authorization': `Bearer ${token}` },
                                                                                                                                                                                body: JSON.stringify({ job_id: job.id, talent_id: talentId, gross_amount_usd: gross })
                                                                                                                                                                                    });
                                                                                                                                                                                        const data = await res.json();
                                                                                                                                                                                            if (res.ok) {
                                                                                                                                                                                                  alert(`Application sent! Contract ${data.contract_id} created - waiting for client to fund escrow`);
                                                                                                                                                                                                        setActiveContractId(data.contract_id);
                                                                                                                                                                                                            } else {
                                                                                                                                                                                                                  // Talent can't create contract - show client flow instead
                                                                                                                                                                                                                        alert(`Note: In this design client creates contract. Tell client your ID: ${talentId} to hire you for job ${job.id}`);
                                                                                                                                                                                                                            }
                                                                                                                                                                                                                              };

                                                                                                                                                                                                                                if (!token) return <div className="p-10 text-white">Please login</div>;

                                                                                                                                                                                                                                  return (
                                                                                                                                                                                                                                      <div className="min-h-screen bg-black text-white p-6 space-y-8">
                                                                                                                                                                                                                                            <div className="flex justify-between items-center">
                                                                                                                                                                                                                                                    <h1 className="text-3xl font-black">AI Talent Dashboard</h1>
                                                                                                                                                                                                                                                            <button onClick={handleConnectStripe} className="bg-green-600 hover:bg-green-700 px-4 py-2 rounded font-bold text-sm">Connect Stripe to Receive 90%</button>
                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                        {profile && <p className="text-zinc-400 text-sm">Logged as {profile.email} | {profile.role} | ID: {profile.user_id}</p>}

                                                                                                                                                                                                                                                                              <div className="grid grid-cols-1 lg:grid-cols-2 gap-8">
                                                                                                                                                                                                                                                                                      <div className="space-y-6">
                                                                                                                                                                                                                                                                                                <div className="bg-zinc-900 border border-zinc-800 p-6 rounded-xl">
                                                                                                                                                                                                                                                                                                            <h3 className="font-bold mb-3">Open Jobs (Search by skill)</h3>
                                                                                                                                                                                                                                                                                                                        <div className="flex gap-2 mb-4">
                                                                                                                                                                                                                                                                                                                                      <input id="skillFilter" placeholder="Filter skill e.g. PyTorch" className="flex-1 bg-black border border-zinc-700 p-2 rounded text-sm" />
                                                                                                                                                                                                                                                                                                                                                    <button onClick={async () => {
                                                                                                                                                                                                                                                                                                                                                                    const skill = (document.getElementById('skillFilter') as any).value;
                                                                                                                                                                                                                                                                                                                                                                                    const res = await fetch(`http://localhost:8000/api/v1/jobs/search?skill=${skill}`);
                                                                                                                                                                                                                                                                                                                                                                                                    const data = await res.json();
                                                                                                                                                                                                                                                                                                                                                                                                                    setJobs(data.results || []);
                                                                                                                                                                                                                                                                                                                                                                                                                                  }} className="bg-zinc-800 px-4 py-2 rounded text-sm">Search</button>
                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                          {jobs.map((j: any) => (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <div key={j.id} className="border-b border-zinc-800 py-3">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <p className="font-bold">{j.title}</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <p className="text-xs text-zinc-500">{j.company} - ${j.budget} - {j.skills?.join(', ')}</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <button onClick={() => applyToJob(j)} className="mt-2 bg-purple-600 hover:bg-purple-700 px-3 py-1 rounded text-xs">Apply / Show Talent ID</button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      {activeContractId? (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <ContractView contractId={activeContractId} token={token} isClient={false} />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ) : (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <div className="bg-zinc-900 border border-zinc-800 p-6 rounded-xl">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <p className="text-zinc-400 text-sm">Contract ID from client:</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <input placeholder="Paste contract_id to view escrow + chat" className="w-full bg-black border border-zinc-700 p-2 rounded mt-3" onKeyDown={e => { if (e.key === 'Enter') setActiveContractId((e.target as any).value); }} />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <div className="mt-6 p-4 bg-black border border-zinc-800 rounded text-xs text-zinc-500">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <p className="font-bold text-white mb-1">How escrow works:</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <p>1. Client funds gross amount (e.g. $2500)</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <p>2. Platform holds it - 10% fee = $250</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <p>3. Client clicks Release</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <p>4. You get 90% = $2250 via Stripe Connect Transfer</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }